# Kimia Farma Performance Analysis 2020–2023

In [2]:
import pandas as pd
import numpy as np

In [3]:
df_transaction = pd.read_csv('/kimia-farma-dashboard/raw/kf_final_transaction.csv')
df_transaction.head()

,transaction_id,date,branch_id,customer_name,product_id,price,discount_percentage,rating
0,TRX5844188,9/7/2023,88605,Elizabeth Thomas,KF260,118700,0.05,3.0
1,TRX6182886,11/7/2022,27840,Andrew Martinez,KF492,751900,0.07,4.8
2,TRX7691180,5/30/2023,62913,Charles Reynolds,KF540,744200,0.03,3.3
3,TRX3205743,11/28/2022,31604,Casey Cochran,KF389,761700,0.06,3.5
4,TRX3644533,5/28/2023,20322,Rebecca Moore,KF854,681000,0.13,4.1

In [4]:
df_branch = pd.read_csv('/kimia-farma-dashboard/raw/kf_kantor_cabang.csv')
df_branch.head()

,branch_id,branch_category,branch_name,kota,provinsi,rating
0,63116,Klinik-Apotek-Laboratorium,Kimia Farma - Klinik-Apotek-Laboratorium,Ciamis,Jawa Barat,4.7
1,31494,Klinik-Apotek-Laboratorium,Kimia Farma - Klinik-Apotek-Laboratorium,Gorontalo,Gorontalo,4.6
2,27840,Apotek,Kimia Farma - Apotek,Denpasar,Bali,4.3
3,44209,Klinik & Apotek,Kimia Farma - Klinik & Apotek,Cilacap,Jawa Tengah,4.5
4,73710,Apotek,Kimia Farma - Apotek,Probolinggo,Jawa Timur,4.0

In [5]:
df_product = pd.read_csv('/kimia-farma-dashboard/raw/kf_product.csv') 
df_product.head()

,product_id,product_name,product_category,price
0,KF162,"Anti-inflammatory and antirheumatic products, ...",M01AE,840200
1,KF374,"Anti-inflammatory and antirheumatic products, ...",R03,867500
2,KF801,"Other analgesics and antipyretics, Salicylic a...",N05C,530300
3,KF519,"Other analgesics and antipyretics, Pyrazolones...",M01AE,626400
4,KF679,"Psycholeptics drugs, Anxiolytic drugs",M01AE,924800

In [6]:
df_inventory = pd.read_csv('/kimia-farma-dashboard/raw/kf_inventory.csv')
df_inventory.head()

,Inventory_ID,branch_id,product_id,product_name,opname_stock
0,INV1162281,12369,KF240,"Psycholeptics drugs, Anxiolytic drugs",86
1,INV3776318,95982,KF190,"Psycholeptics drugs, Anxiolytic drugs",74
2,INV7296268,20322,KF751,"Other analgesics and antipyretics, Pyrazolones...",71
3,INV1114840,20242,KF881,"Other analgesics and antipyretics, Salicylic a...",10
4,INV9288151,75963,KF818,"Anti-inflammatory and antirheumatic products, ...",87

In [7]:
print('transaction :', df_transaction.shape)
print('branch      :', df_branch.shape)
print('product     :', df_product.shape)
print('inventory   :', df_inventory.shape)

transaction : (672458, 8)
branch      : (1725, 6)
product     : (150, 4)
inventory   : (1035000, 5)

In [8]:
print('transaction info:', df_transaction.info())
print('branch info     :', df_branch.info())
print('product info    :', df_product.info())
print('inventory info  :', df_inventory.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 672458 entries, 0 to 672457
Data columns (total 8 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   transaction_id       672458 non-null  object
 1   date                 672458 non-null  object
 2   branch_id            672458 non-null  int64
 3   customer_name        672458 non-null  object
 4   product_id           672458 non-null  object
 5   price                672458 non-null  int64
 6   discount_percentage  672458 non-null  float64
 7   rating               672458 non-null  float64
dtypes: float64(2), int64(2), object(4)
memory usage: 41.0+ MB
transaction info: None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1725 entries, 0 to 1724
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   branch_id        1725 non-null   int64
 1   branch_category  1725 non-null   object
 2   branch_name      1725 non-null   object
 3   kota             1725 non-null   object
 4   provinsi         1725 non-null   object
 5   rating           1725 non-null   float64
dtypes: float64(1), int64(1), object(4)
memory usage: 81.0+ KB
branch info     : None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 4 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   product_id        150 non-null    object
 1   product_name      150 non-null    object
 2   product_category  150 non-null    object
 3   price             150 non-null    int64
dtypes: int64(1), object(3)
memory usage: 4.8+ KB
product info    : None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1035000 entries, 0 to 1034999
Data columns (total 5 columns):
 #   Column        Non-Null Count    Dtype
---  ------        --------------    -----
 0   Inventory_ID  1035000 non-null  object
 1   branch_id     1035000 non-null  int64
 2   product_id    1035000 non-null  object
 3   product_name  1035000 non-null  object
 4   opname_stock  1035000 non-null  int64
dtypes: int64(2), object(3)
memory usage: 39.5+ MB
inventory info  : None

In [9]:
print('Missing values in transaction :' + str(df_transaction.isnull().sum()))
print('\nMissing values in branch      :' + str(df_branch.isnull().sum()))
print('\nMissing values in product     :' + str(df_product.isnull().sum()))
print('\nMissing values in inventory   :' + str(df_inventory.isnull().sum()))

Missing values in transaction :transaction_id         0
date                   0
branch_id              0
customer_name          0
product_id             0
price                  0
discount_percentage    0
rating                 0
dtype: int64

Missing values in branch      :branch_id          0
branch_category    0
branch_name        0
kota               0
provinsi           0
rating             0
dtype: int64

Missing values in product     :product_id          0
product_name        0
product_category    0
price               0
dtype: int64

Missing values in inventory   :Inventory_ID    0
branch_id       0
product_id      0
product_name    0
opname_stock    0
dtype: int64

In [10]:
print('Duplicates in transaction :', df_transaction.duplicated().sum())
print('Duplicates in branch      :', df_branch.duplicated().sum())
print('Duplicates in product     :', df_product.duplicated().sum())
print('Duplicates in inventory   :', df_inventory.duplicated().sum())

Duplicates in transaction : 0
Duplicates in branch      : 0
Duplicates in product     : 0
Duplicates in inventory   : 0

In [11]:
df_transaction['date'] = pd.to_datetime(df_transaction['date'])
df_transaction['date'].head()

0   2023-09-07
1   2022-11-07
2   2023-05-30
3   2022-11-28
4   2023-05-28
Name: date, dtype: datetime64[ns]

In [12]:
df_transaction['year']       = df_transaction['date'].dt.year
df_transaction['month']      = df_transaction['date'].dt.month
df_transaction['month_name'] = df_transaction['date'].dt.strftime('%B')
df_transaction['quarter']    = df_transaction['date'].dt.quarter
df_transaction["day_of_week"] = df_transaction['date'].dt.day_name()
df_transaction[['date', 'year', 'month', 'month_name', 'quarter']].head()

        date  year  month month_name  quarter
0 2023-09-07  2023      9  September        3
1 2022-11-07  2022     11   November        4
2 2023-05-30  2023      5        May        2
3 2022-11-28  2022     11   November        4
4 2023-05-28  2023      5        May        2

In [13]:
df_transaction['nett_sales']  = df_transaction['price'] * (1 - df_transaction['discount_percentage'])

df_transaction[['price', 'discount_percentage', 'nett_sales']].head()

    price  discount_percentage  nett_sales
0  118700                 0.05    112765.0
1  751900                 0.07    699267.0
2  744200                 0.03    721874.0
3  761700                 0.06    715998.0
4  681000                 0.13    592470.0

In [14]:
print(df_branch['provinsi'].unique())

['Jawa Barat' 'Gorontalo' 'Bali' 'Jawa Tengah' 'Jawa Timur' 'Aceh' 'Riau'
 'Kalimantan Selatan' 'Sulawesi Utara' 'Sumatera Utara' 'Sumatera Barat'
 'Nusa Tenggara Barat' 'Kalimantan Utara' 'Sumatera Selatan'
 'Kepulauan Riau' 'Kalimantan Timur' 'Kalimantan Tengah' 'Sulawesi Tengah'
 'Maluku' 'Banten' 'Kalimantan Barat' 'DKI Jakarta' 'Maluku Utara'
 'Sulawesi Selatan' 'DI Yogyakarta' 'Papua' 'Sulawesi Tenggara'
 'Bangka Belitung' 'Nusa Tenggara Timur' 'Jambi' 'Papua Barat']

In [15]:
print(df_product['product_category'].unique())

['M01AE' 'R03' 'N05C' 'N05B' 'N02BE/B' 'R06' 'N02BA' 'M01AB']

In [16]:
print(df_product['product_name'].unique())

['Anti-inflammatory and antirheumatic products, non-steroids, Propionic acid derivatives'
 'Anti-inflammatory and antirheumatic products, non-steroids, Acetic acid derivatives and related substances'
 'Other analgesics and antipyretics, Salicylic acid and derivatives'
 'Other analgesics and antipyretics, Pyrazolones and Anilides'
 'Psycholeptics drugs, Anxiolytic drugs'
 'Drugs for obstructive airway diseases'
 'Psycholeptics drugs, Hypnotics and sedatives drugs'
 'Antihistamines for systemic use']

In [17]:
df_branch = df_branch.rename(columns={
    'kota'      : 'city',
    'provinsi'  : 'province'
})

In [21]:
print('Before:', df_inventory.shape)

df_inventory = df_inventory.drop_duplicates()
print('After drop_duplicates:', df_inventory.shape)

print(df_inventory.isnull().sum())

Before: (1035000, 5)
After drop_duplicates: (1035000, 5)
inventory_id    0
branch_id       0
product_id      0
product_name    0
stock_qty       0
dtype: int64

In [18]:
df_inventory = df_inventory.rename(columns={
    'opname_stock': 'stock_qty',
    'Inventory_ID': 'inventory_id'
})

In [20]:
df_transaction.to_csv('d:/kimia-farma-dashboard/final/kf_transaction_clean.csv', index=False)
df_branch.to_csv('d:/kimia-farma-dashboard/final/kf_branch_clean.csv', index=False)
df_product.to_csv('d:/kimia-farma-dashboard/final/kf_product_clean.csv', index=False)
df_inventory.to_csv('d:/kimia-farma-dashboard/final/kf_inventory_clean.csv', index=False)

print('All 4 tables saved!')

All 4 tables saved!